name: Pre Release (Check Tag & Dry Only Publish Pub Dev)

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: development
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout V3
        uses: actions/checkout@v3
      - name: Check TAG Version
        run: |
          echo "TAG VERSION: $GITHUB_REF_NAME"
          echo "TAG VERSION: ${{  github.ref_name }}"
      - name: Check Pre Release Pub Dev
        uses: k-paxian/dart-package-publisher@master
        with:
          accessToken: ${{ secrets.PUB_ACCESS_TOKEN }}
          refreshToken: ${{ secrets.PUB_REFRESH_TOKEN }}
          flutterBranch: 'flutter-3.19-candidate.5'
          dryRunOnly: true
          force: false
          
